services:
  - type: web
    name: portfolio-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn demoproject.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9